export const SET_REPORT_ROWS = 'SET_REPORT_ROWS';
export const SET_CAR_DATA = 'SET_CAR_DATA';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const SET_REPORT_ROW_ANSWER = 'SET_REPORT_ROW_ANSWER';
