export const SET_REPORT_ROWS = 'SET_REPORT_ROWS';
export const SET_CAR_DATA = 'SET_CAR_DATA';
export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const SET_REPORT_STRUCTURE = 'SET_REPORT_STRUCTURE';
export const SET_REPORT_ROW_ANSWER = 'SET_REPORT_ROW_ANSWER';
export const SET_ERROR = 'SET_ERROR';
export const DELETE_ERROR = 'DELETE ERROR';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SET_STATE = 'SET_STATE';
export const SET_REPORT_ROW_IMAGE = 'SET_REPORT_ROW_IMAGE';
export const SET_REPORT_ROW_ADDITIONAL_INPUT =
  'SET_REPORT_ROW_ADDITIONAL_INPUT';
export const SET_REPORT_ROW_COMMENT = 'SET_REPORT_ROW_COMMENT';
export const SET_REPORT_ROW_LEFTRIGHT_INPUT = 'SET_REPORT_ROW_LEFTRIGHT_INPUT';
export const CHANGE_REPORT_ROW_IMAGE = 'CHANGE_REPORT_ROW_IMAGE';
export const REMOVE_REPORT_ROW_IMAGE = 'REMOVE_REPORT_ROW_IMAGE';
